spring:
  datasource:
    username: instagram
    password: instagram
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 120000
      idleTimeout: 30000
      poolName: instagram
      maxLifetime: 2000000
      connectionTimeout: 60000
      connectionInitSql: ALTER SESSION SET CURRENT_SCHEMA = instagram
