server.port: 8081

spring:
  datasource:
    username: instagram
    password: instagram
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
  jpa:
    properties:
      hibernate:
        default_schema: instagram
        ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
hibernate:
  dialect: org.hibernate.dialect.Oracle10gDialect

secret: instagramsecret


